#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Dec 22, 2024 07:15:02 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list {
    open_png "./icons/open.png"
    restart_png "./icons/restart.png"
    save_png "./icons/save.png"
    open_png "./icons/open.png"
    refresh_png "./icons/refresh.png"
    clone_png "./icons/clone.png"
    rename_png "./icons/rename.png"
    open_png "./icons/open.png"
    save_png "./icons/save.png"
    restart_png "./icons/restart.png"
    record_png "./icons/record.png"
    start_marker_png "./icons/start_marker.png"
    end_marker_png "./icons/end_marker.png"
    play_png "./icons/play.png"
    icon_png "./icons/icon.png"
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
###########################################
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
###########################################
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) waldorf



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m53 -background gray82 -highlightbackground gray82 -highlightcolor black
    wm focusmodel $top passive
    wm geometry $top 947x680+523+232
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m53" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {Arial} -size 9" -tearoff 0
    label "$top.lab57" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Arial} -size 9" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Saving..."
    vTcl:DefineAlias "$top.lab57" "label_saving" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu47" \
        -image open_png -compound center
    vTcl:DefineAlias "$top.tBu47" "button_open_project" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Project"
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab47" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Video"
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Output"
    vTcl:DefineAlias "$top.lab50" "Label4" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$top.tEn49" \
        -font "-family {Arial} -size 9" -cursor xterm
    vTcl:DefineAlias "$top.tEn49" "entry_video_input" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$top.tEn50" \
        -font "-family {Arial} -size 9" -cursor xterm
    vTcl:DefineAlias "$top.tEn50" "entry_video_output" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu56" \
        -image restart_png -compound center
    vTcl:DefineAlias "$top.tBu56" "button_play_script" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tBu56 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Ctrl+ENTER}
    }
    ttk::entry "$top.tEn48" \
        -font "-family {Arial} -size 9" -cursor xterm
    vTcl:DefineAlias "$top.tEn48" "entry_project_name" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab55" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "Script editor"
    vTcl:DefineAlias "$top.lab55" "Label7" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu48" \
        -text "..." -image save_png -compound left
    vTcl:DefineAlias "$top.tBu48" "button_save_as_project" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu53" \
        -image open_png -compound center
    vTcl:DefineAlias "$top.tBu53" "button_select_output" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "Moshers"
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu55" \
        -image refresh_png -compound center
    vTcl:DefineAlias "$top.tBu55" "button_reload_script_list" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu65" \
        -image clone_png -compound center
    vTcl:DefineAlias "$top.tBu65" "button_clone" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu66" \
        -image rename_png -compound center
    vTcl:DefineAlias "$top.tBu66" "button_rename_script" vTcl:WidgetProc "Toplevel1" 1
    ttk::checkbutton "$top.tCh57" \
        -variable "is_auto_rename" -text "Auto rename" -compound top
    vTcl:DefineAlias "$top.tCh57" "checkbutton_auto_rename" vTcl:WidgetProc "Toplevel1" 1
    ttk::checkbutton "$top.tCh47" \
        -variable "is_mute" -text "Mute" -compound center
    vTcl:DefineAlias "$top.tCh47" "checkbutton_mute" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$top.scr47" \
        -background gray82 -height 75 -highlightbackground gray82 \
        -highlightcolor black -width 125
    vTcl:DefineAlias "$top.scr47" "listbox_scripts" vTcl:WidgetProc "Toplevel1" 1

    $top.scr47.01 configure -activestyle none \
        -background #eaeaea \
        -cursor arrow \
        -disabledforeground #9d9d9d \
        -exportselection 0 \
        -font "-family {Arial} -size 10" \
        -foreground black \
        -height 3 \
        -highlightbackground gray82 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c9c9c9 \
        -selectforeground black \
        -selectmode single \
        -width 10
    ttk::button "$top.tBu54" \
        -text "Edit" -compound left
    vTcl:DefineAlias "$top.tBu54" "button_edit_script" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu52" \
        -image open_png -compound center
    vTcl:DefineAlias "$top.tBu52" "button_select_video" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu49" \
        -image save_png -compound left
    vTcl:DefineAlias "$top.tBu49" "button_save_project" vTcl:WidgetProc "Toplevel1" 1
    labelframe "$top.lab59" \
        -font "-family {Arial} -size 9" -foreground black -background gray82 \
        -height 111 -highlightbackground gray82 -highlightcolor black \
        -width 366
    vTcl:DefineAlias "$top.lab59" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab59
    label "$site_3_0.lab56" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "10x"
    vTcl:DefineAlias "$site_3_0.lab56" "label_speed" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$site_3_0.tSc48" \
        -from 0.1 -to 4 -length 79
    vTcl:DefineAlias "$site_3_0.tSc48" "scale_speed" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu59" \
        -image restart_png -compound center
    vTcl:DefineAlias "$site_3_0.tBu59" "button_restart_video" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu59 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Restart}
    }
    ttk::button "$site_3_0.tBu51" \
        -text "Record" -image record_png -compound left
    vTcl:DefineAlias "$site_3_0.tBu51" "button_record" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab58" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "FPS: 25"
    vTcl:DefineAlias "$site_3_0.lab58" "label_fps" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu58" \
        -text "-10s" -compound left
    vTcl:DefineAlias "$site_3_0.tBu58" "button_seek_back_10s" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu60" \
        -text "-2s" -compound left
    vTcl:DefineAlias "$site_3_0.tBu60" "button_seek_back_2s" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu64" \
        -text "+10s" -compound left
    vTcl:DefineAlias "$site_3_0.tBu64" "button_seek_10s" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu61" \
        -text "+2s" -compound left
    vTcl:DefineAlias "$site_3_0.tBu61" "button_seek_2s" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu63" \
        -text "+1f" -compound left
    vTcl:DefineAlias "$site_3_0.tBu63" "button_seek_1f" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu62" \
        -text "-10f" -compound left
    vTcl:DefineAlias "$site_3_0.tBu62" "button_seek_back_10f" vTcl:WidgetProc "Toplevel1" 1
    canvas "$site_3_0.can47" \
        -background gray82 -borderwidth 2 -closeenough 1.0 -height 17 \
        -highlightbackground #2e2e2e -highlightcolor black \
        -insertbackground black -selectbackground #d9d9d9 \
        -selectforeground black -width 0
    vTcl:DefineAlias "$site_3_0.can47" "canvas_end_mark" vTcl:WidgetProc "Toplevel1" 1
    canvas "$site_3_0.can63" \
        -background gray82 -borderwidth 2 -closeenough 1.0 -height 17 \
        -highlightbackground #2e2e2e -highlightcolor black \
        -insertbackground black -selectbackground #d9d9d9 \
        -selectforeground black -width 0
    vTcl:DefineAlias "$site_3_0.can63" "canvas_start_mark" vTcl:WidgetProc "Toplevel1" 1
    ttk::scale "$site_3_0.tSc47" \
        -length 335
    vTcl:DefineAlias "$site_3_0.tSc47" "scale_progress" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu57" \
        -image start_marker_png -compound center
    vTcl:DefineAlias "$site_3_0.tBu57" "button_start_mark" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Start marker}
    }
    ttk::button "$site_3_0.tBu67" \
        -image end_marker_png -compound center
    vTcl:DefineAlias "$site_3_0.tBu67" "button_end_mark" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.tBu67 <<SetBalloon>> {
        set ::vTcl::balloon::%W {End marker}
    }
    label "$site_3_0.lab63" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background gray82 -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "00:00:12.23"
    vTcl:DefineAlias "$site_3_0.lab63" "label_progress" vTcl:WidgetProc "Toplevel1" 1
    label "$site_3_0.lab53" \
        -activebackground #d9d9d9 -activeforeground black -anchor ne \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "00:01:12.80"
    vTcl:DefineAlias "$site_3_0.lab53" "label_total_time" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu50" \
        -image play_png -compound center
    vTcl:DefineAlias "$site_3_0.tBu50" "button_play" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab56 \
        -in $site_3_0 -x 331 -y 78 -width 27 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tSc48 \
        -in $site_3_0 -x 247 -y 85 -width 79 -relwidth 0 -height 13 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 108 -y 8 -width 24 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu51 \
        -in $site_3_0 -x 257 -y 8 -width 93 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.lab58 \
        -in $site_3_0 -x 143 -y 7 -width 55 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 72 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu60 \
        -in $site_3_0 -x 96 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu64 \
        -in $site_3_0 -x 202 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu61 \
        -in $site_3_0 -x 178 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu63 \
        -in $site_3_0 -x 154 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu62 \
        -in $site_3_0 -x 120 -y 78 -width 25 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.can47 \
        -in $site_3_0 -x 216 -y 41 -width 2 -height 19 -anchor nw \
        -bordermode ignore
    place $site_3_0.can63 \
        -in $site_3_0 -x 150 -y 41 -width 2 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tSc47 \
        -in $site_3_0 -x 17 -y 43 -width 335 -relwidth 0 -height 14 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 16 -y 78 -width 20 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu67 \
        -in $site_3_0 -x 35 -y 78 -width 20 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.lab63 \
        -in $site_3_0 -x 13 -y 58 -width 174 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.lab53 \
        -in $site_3_0 -x 271 -y 58 -width 85 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 16 -y 8 -width 93 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore
    label "$top.lab48" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground #988e1f \
        -highlightbackground gray82 -highlightcolor black \
        -text "Recording overwrite output file"
    vTcl:DefineAlias "$top.lab48" "label_output_status" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab51" \
        -activebackground #d9d9d9 -activeforeground black -anchor sw \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "Console output"
    vTcl:DefineAlias "$top.lab51" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab54" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 8" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "Parameters (-sp)"
    vTcl:DefineAlias "$top.lab54" "Label6" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$top.scr49" \
        -borderwidth 2 -relief groove -background gray82 -height 75 \
        -highlightbackground gray82 -highlightcolor black -width 125
    vTcl:DefineAlias "$top.scr49" "scrolledText_console" vTcl:WidgetProc "Toplevel1" 1

    $top.scr49.01 configure -background #444444 \
        -font "-family {Courier New} -size 9" \
        -foreground black \
        -height 3 \
        -highlightbackground #7d7d7d \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #797979 \
        -selectforeground black \
        -width 10 \
        -wrap none
    ttk::entry "$top.tEn51" \
        -font "-family {Arial} -size 9" -cursor xterm
    vTcl:DefineAlias "$top.tEn51" "entry_script_parameters" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$top.scr48" \
        -borderwidth 2 -relief groove -background gray82 -height 75 \
        -highlightbackground gray82 -highlightcolor black -width 125
    vTcl:DefineAlias "$top.scr48" "scrolledtext_script_editor" vTcl:WidgetProc "Toplevel1" 1

    $top.scr48.01 configure -background #ffffff \
        -font "-family {Courier New} -size 9" \
        -foreground black \
        -height 3 \
        -highlightbackground gray82 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -maxundo 9999 \
        -padx 3 \
        -pady 2 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -tabstyle wordprocessor \
        -undo 1 \
        -width 10 \
        -wrap none
    label "$top.lab60" \
        -activebackground #d9d9d9 -activeforeground black -anchor e \
        -background gray82 -compound left -cursor hand2 \
        -disabledforeground #9d9d9d -font "-family {Segoe UI} -size 8" \
        -foreground #515151 -highlightbackground gray82 -highlightcolor black \
        -text "Report an issue"
    vTcl:DefineAlias "$top.lab60" "label_issue" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab61" \
        -activebackground #d9d9d9 -activeforeground #a0a0a0 \
        -background gray82 -compound left -cursor hand2 \
        -disabledforeground #9d9d9d -font "-family {Segoe UI} -size 8" \
        -foreground #515151 -highlightbackground gray82 -highlightcolor black \
        -text "About"
    vTcl:DefineAlias "$top.lab61" "label_about" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab57 \
        -in $top -x 370 -y 140 -width 50 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu47 \
        -in $top -x 243 -y 8 -width 49 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab49 \
        -in $top -x 12 -y 10 -width 54 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab47 \
        -in $top -x 18 -y 40 -width 46 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab50 \
        -in $top -x 11 -y 70 -width 52 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tEn49 \
        -in $top -x 60 -y 38 -width 234 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tEn50 \
        -in $top -x 60 -y 68 -width 234 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu56 \
        -in $top -x 305 -y 138 -width 60 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tEn48 \
        -in $top -x 60 -y 8 -width 177 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab55 \
        -in $top -x 221 -y 144 -width 74 -relwidth 0 -height 17 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu48 \
        -in $top -x 300 -y 8 -width 49 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu53 \
        -in $top -x 300 -y 69 -width 49 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab52 \
        -in $top -x 10 -y 120 -width 53 -relwidth 0 -height 16 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu55 \
        -in $top -x 180 -y 121 -width 30 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu65 \
        -in $top -x 108 -y 121 -width 27 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu66 \
        -in $top -x 145 -y 121 -width 27 -relwidth 0 -height 18 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tCh57 \
        -in $top -x 59 -y 93 -width 124 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tCh47 \
        -in $top -x 882 -y 119 -width 58 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.scr47 \
        -in $top -x 10 -y 140 -width 199 -relwidth 0 -height 355 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu54 \
        -in $top -x 374 -y 138 -width 60 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu52 \
        -in $top -x 300 -y 39 -width 49 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tBu49 \
        -in $top -x 357 -y 9 -width 49 -relwidth 0 -height 24 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab59 \
        -in $top -x 572 -y 8 -width 366 -relwidth 0 -height 111 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab48 \
        -in $top -x 180 -y 93 -width 191 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab51 \
        -in $top -x 10 -y 507 -width 466 -relwidth 0 -height 13 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab54 \
        -in $top -x 475 -y 140 -width 92 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.scr49 \
        -in $top -x 10 -y 520 -width 932 -relwidth 0 -height 153 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.tEn51 \
        -in $top -x 571 -y 139 -width 369 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.scr48 \
        -in $top -x 221 -y 166 -width 717 -relwidth 0 -height 327 \
        -relheight 0 -anchor nw -bordermode ignore
    place $top.lab60 \
        -in $top -x 792 -y 500 -width 92 -relwidth 0 -height 13 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab61 \
        -in $top -x 890 -y 500 -width 48 -relwidth 0 -height 13 -relheight 0 \
        -anchor nw -bordermode ignore

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background gray82 -highlightbackground gray82 -highlightcolor black
    wm focusmodel $top passive
    wm geometry $top 225x243+961+459
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2564 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "About"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "ToplevelAbout" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::button "$top.tBu71" \
        -text "OK" -compound left
    vTcl:DefineAlias "$top.tBu71" "button_ok" vTcl:WidgetProc "ToplevelAbout" 1
    label "$top.lab67" \
        -activebackground #d9d9d9 -activeforeground black -anchor n \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "a front-end for"
    vTcl:DefineAlias "$top.lab67" "Label10" vTcl:WidgetProc "ToplevelAbout" 1
    label "$top.lab74" \
        -activebackground #d9d9d9 -activeforeground black -anchor n \
        -background gray82 -compound left -cursor hand2 \
        -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 9 -underline 1" -foreground black \
        -highlightbackground gray82 -highlightcolor black -text "ffglitch"
    vTcl:DefineAlias "$top.lab74" "label_ffglitch" vTcl:WidgetProc "ToplevelAbout" 1
    button "$top.but73" \
        -activebackground #d9d9d9 -activeforeground black -background #b9b9b9 \
        -disabledforeground #9d9d9d -font "-family {Segoe UI} -size 9" \
        -foreground black -highlightbackground #ff7376 -highlightcolor black \
        -image icon_png -overrelief flat -relief flat -text "Button"
    vTcl:DefineAlias "$top.but73" "Button2" vTcl:WidgetProc "ToplevelAbout" 1
    label "$top.lab68" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background gray82 -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "made by Ramiro Polla"
    vTcl:DefineAlias "$top.lab68" "Label11" vTcl:WidgetProc "ToplevelAbout" 1
    label "$top.lab66" \
        -activebackground #d9d9d9 -activeforeground black -background gray82 \
        -compound left -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 9" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "made by pawelzwronek"
    vTcl:DefineAlias "$top.lab66" "Label9" vTcl:WidgetProc "ToplevelAbout" 1
    label "$top.lab62" \
        -activebackground #d9d9d9 -activeforeground black -background gray82 \
        -compound left -cursor hand2 -disabledforeground #9d9d9d \
        -font "-family {Segoe UI} -size 14 -underline 1" -foreground black \
        -highlightbackground gray82 -highlightcolor black \
        -text "LiveMosher 1.0"
    vTcl:DefineAlias "$top.lab62" "label_name" vTcl:WidgetProc "ToplevelAbout" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu71 \
        -in $top -x 79 -y 201 -width 68 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab67 \
        -in $top -x 54 -y 145 -width 85 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab74 \
        -in $top -x 136 -y 145 -width 44 -relwidth 0 -height 27 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.but73 \
        -in $top -x 65 -y 12 -width 96 -relwidth 0 -height 69 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab68 \
        -in $top -x 56 -y 162 -width 122 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab66 \
        -in $top -x 40 -y 114 -width 150 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore
    place $top.lab62 \
        -in $top -x 6 -y 84 -width 213 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
